#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -gt 0 ] ; then
  if [ "$#" -ne 1 ] || [ "${1:-}" = "--help" ] ; then
    echo "Usage: $0 [builder]" >&2
    exit 1
  else
    export BUILDER=$1
  fi

  if [ ! -d "/usr/lib/caketop-builder/ansible/builders/$BUILDER" ] ; then
    echo "ERROR: Unknown builder '$BUILDER'" >&2
    exit 1
  fi
fi

ANSIBLE_PLAYBOOK_ARGS=${ANSIBLE_PLAYBOOK_ARGS:--v}
exec ansible-playbook $ANSIBLE_PLAYBOOK_ARGS /usr/lib/caketop-builder/ansible/builder-playbook.yml
