#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 1 ] ; then
  BUILDER=disk_image
elif [ "$#" -ne 1 ] || [ "${1:-}" = "--help" ] ; then
  echo "Usage: $0 [builder]" >&2
  exit 1
else
  BUILDER=$1
fi

if [ ! -d "/usr/lib/caketop-builder/ansible/builders/$BUILDER" ] ; then
  echo "ERROR: Unknown builder '$BUILDER'" >&2
  exit 1
fi

exec ansible-playbook -v /usr/lib/caketop-builder/ansible/builder-playbook.yml
