#!/usr/bin/env bash
set -euo pipefail

mtree_keys="uid,gid,mode,size,device,link,sha256"

sha256only() {
  sha256sum "$@" | cut -d' ' -f1
}

deterministic_mtree() {
  (cd "$1" && mtree -c -k "$mtree_keys" | mtree -C -k "$mtree_keys" | sort)
}

checksums=()

while [ "$#" -gt 0 ] ; do
  path=$1
  shift
  if [ "$path" = "-" ] ; then
    checksums+=($(sha256only))
  elif [ -f "$path" ] ;then
    checksums+=($(sha256only "$path"))
  elif [ -d "$path" ] ; then
    checksums+=($(deterministic_mtree "$path" | sha256only))
  elif [ -e "$path" ] ; then
    echo "ERROR: don't know how to checksum $path" >&2
    exit 1
  fi
done

if [ "${#checksums[@]}" -gt 1 ] ; then
  echo "${checksums[@]}" | sha256only
elif [ "${#checksums[@]}" -gt 0 ] ; then
  echo "${checksums[@]}"
fi
